language: php

php:
    - 7.4
    - 8.0

matrix:
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
    - composer self-update
    - composer --version
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then php php-cs-fixer.phar --version; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar; fi

install:
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source $COMPOSER_FLAGS

script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then php php-cs-fixer.phar fix --dry-run -v; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then bin/simple-phpunit --coverage-clover build/logs/clover.xml; fi
    - if [ "$TRAVIS_PHP_VERSION" != "7.4" ]; then bin/simple-phpunit; fi

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then php php-coveralls.phar -v; fi
